<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Gimbur.Core</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Kjarni\Kjarni.fsproj" />
    <ProjectReference Include="..\Gimbur.Rules\Gimbur.Rules.csproj" />
  </ItemGroup>

</Project>
