<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowMissingPrunePackageData>true</AllowMissingPrunePackageData>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Kjarni/Kjarni.fsproj" />
    <ProjectReference Include="../Gimbur/Gimbur.csproj" />
  </ItemGroup>

</Project>
